services:
  mongo:
    image: mongo:7
    container_name: codementor_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: codementor_redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: codementor_backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.example
    environment:
      - MONGO_URI=mongodb://mongo:27017/codementor_ai
      - REDIS_URL=redis://redis:6379
      - CLIENT_URL=http://localhost:5173
      - ENABLE_QUEUE=true
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  worker:
    build: ./backend
    container_name: codementor_worker
    command: npm run worker
    env_file:
      - ./backend/.env.example
    environment:
      - MONGO_URI=mongodb://mongo:27017/codementor_ai
      - REDIS_URL=redis://redis:6379
      - ENABLE_QUEUE=true
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: codementor_frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.example
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
