export const queryKeys = {
  dashboard: ['dashboard'],
  onboardingStatus: ['onboarding-status'],
  roadmap: ['roadmap'],
  reports: ['reports'],
  lesson: (lessonId) => ['lesson', lessonId],
  quiz: (moduleId) => ['quiz', moduleId],
  quizAttempt: (attemptId) => ['quiz-attempt', attemptId],
  mentorHistory: ['mentor-history'],
  mentorAIStatus: ['mentor-ai-status'],
  mentorSuggestions: (lessonId) => ['mentor-suggestions', lessonId],
  projectTasks: (params = {}) => ['project-tasks', params],
  projectTask: (taskId) => ['project-task', taskId],
  interviewQuestions: (params = {}) => ['interview-questions', params],
  interviewAttempts: ['interview-attempts'],
  adminTopics: (params = {}) => ['admin-topics', params],
  adminLessons: (params = {}) => ['admin-lessons', params],
  adminQuestions: (params = {}) => ['admin-questions', params],
  adminInterviewQuestions: (params = {}) => ['admin-interview-questions', params],
  adminTemplates: (params = {}) => ['admin-templates', params]
};
