export const queryKeys = {
  dashboard: ['dashboard'],
  onboardingStatus: ['onboarding-status'],
  roadmap: ['roadmap'],
  reports: ['reports'],
  lesson: (lessonId) => ['lesson', lessonId],
  quiz: (moduleId) => ['quiz', moduleId],
  quizAttempt: (attemptId) => ['quiz-attempt', attemptId],
  mentorHistory: ['mentor-history'],
  mentorAIStatus: ['mentor-ai-status'],
  mentorSuggestions: (lessonId) => ['mentor-suggestions', lessonId],
  projectTasks: (params = {}) => ['project-tasks', params],
  projectTask: (taskId) => ['project-task', taskId],
  interviewQuestions: (params = {}) => ['interview-questions', params],
  interviewAttempts: ['interview-attempts'],
  adminTopics: (params = {}) => ['admin-topics', params],
  adminTopic: (topicId) => ['admin-topic', topicId],
  adminTopicImpact: (topicId) => ['admin-topic-impact', topicId],
  adminLessons: (params = {}) => ['admin-lessons', params],
  adminLesson: (lessonId) => ['admin-lesson', lessonId],
  adminLessonImpact: (lessonId) => ['admin-lesson-impact', lessonId],
  adminQuestions: (params = {}) => ['admin-questions', params],
  adminQuestion: (questionId) => ['admin-question', questionId],
  adminQuestionImpact: (questionId) => ['admin-question-impact', questionId],
  adminInterviewQuestions: (params = {}) => ['admin-interview-questions', params],
  adminInterviewQuestion: (questionId) => ['admin-interview-question', questionId],
  adminInterviewQuestionImpact: (questionId) => ['admin-interview-question-impact', questionId],
  adminTemplates: (params = {}) => ['admin-templates', params],
  adminTemplate: (templateId) => ['admin-template', templateId]
};
